#!/usr/bin/env bash

# Dir
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias p='pwd'

# Python
alias pweb='python -m SimpleHTTPServer'

# Android
alias l=pidcat
alias logcat=pidcat
alias adb_record="adb shell screenrecord /sdcard/recording.mp4 && adb pull /sdcard/recording.mp4 ~/Desktop/recording.mp4"
alias adb_screencap="adb shell screencap -p /sdcard/screen.png && adb pull /sdcard/screen.png ~/Desktop/screen.png"

# Hub
alias git=hub

# Git
alias g='git'
alias gut='git'
alias gaa='git add --all'
alias gl='git pull --prune'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp=push_and_set_upstream
alias gd='git diff'
alias gcp='git cherry-pick'
alias gc='git commit'
alias gca='git add --all && git commit -a'
alias gco='git checkout'
alias gb='git branch'
alias gs='git status -sb' # upgrade your git if -sb breaks for you. it's fun.
alias gaa='git add --all && gs'
alias gf='git fetch --prune'
alias gr='gf && ga && git stash && git pull --rebase && git stash apply'
alias gup='git remote update -p; git merge --ff-only @{u}'
alias ghis='git for-each-ref --count=20 --sort=-committerdate refs/heads/ --format="%(refname:short)"'
alias gu='git fetch && git rebase --autostash'
alias pr=pull_request

# Brew
alias bu='brew upgrade && brew update --all && brew cleanup && brew doctor && brew prune'
alias bcu='brew cask doctor && brew cleanup'

# Mainframer
alias m="mainframer"

# Open
alias o='open .'

function pull_request() {
  push_and_set_upstream
  hub pull-request -o -m $1
}

# Pushes the current branch and sets it to upstream
function push_and_set_upstream() {
  git push -u origin "$(git branch | grep '\*' | cut -d ' ' -f 2)"
}

function make-mp4() {
  ffmpeg -f gif -i $1 $1.mp4
}

function make-gif() {
  ffmpeg -i $1 -vf fps=10,scale=480:-1 $1.gif
}
