#!/usr/bin/env bash

funcs=(
  /usr/local/share/zsh/site-functions
  "$HOMEBREW_PREFIX/share/zsh/site-functions"
  "$HOMEBREW_PREFIX/share/zsh-completions"
)
for func in "${funcs[@]}"; do
  [[ -d $func ]] \
  && [[ $FPATH != *$func* ]] \
  && FPATH=$func:$FPATH
done
