#!/usr/bin/env bash

# Rust
export CARGO_HOME=$HOME/.cargo

# Java
JAVA_HOME="$(/usr/libexec/java_home -v 21)"
export JAVA_HOME

# Kotlin
export KOTLIN_HOME="/usr/local/opt/kotlin/"

# Configure the paths
paths=(
  "$HOME/.bin"                    # User
  /opt/homebrew/bin               # Homebrew
  /usr/local/bin
  "$CARGO_HOME/bin"               # Rust
  "$JAVA_HOME/bin"                # Java
  /opt/homebrew/sbin              # Homebrew sbin
  /usr/local/sbin
  /usr/bin                        # System
  /bin
  /usr/sbin
  /sbin
  "$HOME/.lmstudio/bin"           # LM Studio
)

for search_path in "${paths[@]}"; do
  [[ -d $search_path ]] \
  && [[ ":$PATH:" != *":$search_path:"* ]] \
  && PATH=$PATH:$search_path
done

export PATH
