#!/usr/bin/env bash

# Rust
export CARGO_HOME="$HOME/.cargo"

# Java
JAVA_HOME="$(/usr/libexec/java_home -v 21)"
export JAVA_HOME

# Kotlin
export KOTLIN_HOME="/usr/local/opt/kotlin/"

# Configure the paths
paths=(
  "$HOME/.bin"                    # User
  "$HOMEBREW_PREFIX/bin"          # Homebrew
  /usr/local/bin
  "$CARGO_HOME/bin"               # Rust
  "$JAVA_HOME/bin"                # Java
  "$HOMEBREW_PREFIX/sbin"         # Homebrew sbin
  /usr/local/sbin
  /usr/bin                        # System
  /bin
  /usr/sbin
  /sbin
  "$HOME/.lmstudio/bin"           # LM Studio
  "$HOME/.rd/bin"							    # Rancher
)

new_path=""
for search_path in "${paths[@]}"; do
  [[ -d $search_path ]] \
  && [[ ":$new_path:" != *":$search_path:"* ]] \
  && new_path="${new_path:+$new_path:}$search_path"
done

export PATH="$new_path"
